<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608162136 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE entrainer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE activite ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE activite ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX inscrire_membre_id_session_id_key');
        $this->addSql('ALTER TABLE inscrire ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE inscrire ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE membre ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE membre ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX membre_login_key RENAME TO UNIQ_F6B4FB29AA08CB10');
        $this->addSql('ALTER INDEX membre_email_key RENAME TO UNIQ_F6B4FB29E7927C74');
        $this->addSql('ALTER TABLE roles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE roles ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT session_entraineur_id_fkey');
        $this->addSql('ALTER TABLE session ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE session ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D4F8478A1 FOREIGN KEY (entraineur_id) REFERENCES membre (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE type ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE type ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE entrainer');
        $this->addSql('ALTER TABLE activite ALTER id SET DEFAULT nextval(\'activite_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE activite ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE inscrire ALTER id SET DEFAULT nextval(\'inscrire_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE inscrire ALTER id DROP IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX inscrire_membre_id_session_id_key ON inscrire (membre_id, session_id)');
        $this->addSql('ALTER TABLE membre ALTER id SET DEFAULT nextval(\'membre_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE membre ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_f6b4fb29aa08cb10 RENAME TO membre_login_key');
        $this->addSql('ALTER INDEX uniq_f6b4fb29e7927c74 RENAME TO membre_email_key');
        $this->addSql('ALTER TABLE roles ALTER id SET DEFAULT nextval(\'roles_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE roles ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D4F8478A1');
        $this->addSql('ALTER TABLE session ALTER id SET DEFAULT nextval(\'session_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE session ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT session_entraineur_id_fkey FOREIGN KEY (entraineur_id) REFERENCES membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type ALTER id SET DEFAULT nextval(\'type_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE type ALTER id DROP IDENTITY');
    }
}
