-- Adminer 4.8.1 PostgreSQL 15.14 (Debian 15.14-0+deb12u1) dump

DROP TABLE IF EXISTS "activite";
CREATE TABLE "public"."activite" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    "description" character varying(255) NOT NULL,
    "capacite_max" integer NOT NULL,
    "prix" double precision NOT NULL,
    "nv_difficulte" integer NOT NULL,
    "type_id" integer,
    CONSTRAINT "activite_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "idx_b8755515c54c8c93" ON "public"."activite" USING btree ("type_id");

INSERT INTO "activite" ("id", "nom", "description", "capacite_max", "prix", "nv_difficulte", "type_id") VALUES
(1,	'Football',	'dembele ballon d''or',	11,	50,	2,	1),
(4,	'Tennis',	'tah Challengers le film surcoté avec Zendaya',	2,	20,	1,	2),
(5,	'Kung fu',	'Tristan le cul en l''air',	2,	90,	3,	3);

DROP TABLE IF EXISTS "doctrine_migration_versions";
CREATE TABLE "public"."doctrine_migration_versions" (
    "version" character varying(191) NOT NULL,
    "executed_at" timestamp(0),
    "execution_time" integer,
    CONSTRAINT "doctrine_migration_versions_pkey" PRIMARY KEY ("version")
) WITH (oids = false);

INSERT INTO "doctrine_migration_versions" ("version", "executed_at", "execution_time") VALUES
('DoctrineMigrations\Version20251126154948',	'2025-11-26 15:50:42',	17),
('DoctrineMigrations\Version20251126155407',	'2025-11-26 15:54:14',	73),
('DoctrineMigrations\Version20251126155446',	'2025-11-26 15:54:54',	66),
('DoctrineMigrations\Version20251126155706',	'2025-11-26 15:57:12',	62),
('DoctrineMigrations\Version20251204084206',	'2025-12-04 08:42:16',	33),
('DoctrineMigrations\Version20251218104808',	'2025-12-18 10:48:16',	37),
('DoctrineMigrations\Version20260114150251',	'2026-01-14 15:02:57',	18),
('DoctrineMigrations\Version20260120074516',	'2026-01-20 07:45:21',	35),
('DoctrineMigrations\Version20260120075253',	'2026-01-20 07:52:56',	64),
('DoctrineMigrations\Version20260120094543',	'2026-01-20 09:45:53',	35),
('DoctrineMigrations\Version20260121131558',	'2026-01-21 13:16:03',	27),
('DoctrineMigrations\Version20260121145637',	'2026-01-21 14:59:35',	30);

DROP TABLE IF EXISTS "entrainer";
CREATE TABLE "public"."entrainer" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT "entrainer_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "inscrire";
CREATE TABLE "public"."inscrire" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "membre_id" integer,
    "session_id" integer,
    CONSTRAINT "inscrire_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "idx_84ca37a8613fecdf" ON "public"."inscrire" USING btree ("session_id");

CREATE INDEX "idx_84ca37a86a99f74a" ON "public"."inscrire" USING btree ("membre_id");


DROP TABLE IF EXISTS "membre";
CREATE TABLE "public"."membre" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    "prenom" character varying(255) NOT NULL,
    "login" character varying(180) NOT NULL,
    "roles" json NOT NULL,
    "password" character varying(255) NOT NULL,
    "role_id" integer,
    "email" character varying(180) NOT NULL,
    CONSTRAINT "membre_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uniq_f6b4fb29aa08cb10" UNIQUE ("login"),
    CONSTRAINT "uniq_f6b4fb29e7927c74" UNIQUE ("email")
) WITH (oids = false);

CREATE INDEX "idx_f6b4fb29d60322ac" ON "public"."membre" USING btree ("role_id");

INSERT INTO "membre" ("id", "nom", "prenom", "login", "roles", "password", "role_id", "email") VALUES
(6,	'DUPONT',	'Jean',	'jdupont',	'[]',	'$2y$13$fHco9ocHf8nPl1bZIcw.Pehi26AdlJCP5sjxM91HkL.8IRqz5arcu',	1,	'charles.rubio2006@gmail.com'),
(5,	'RUBIO',	'Charles',	'crubio',	'[]',	'$2y$13$dIetL9iA.LAgJbQ3SNVus.g5Jk7zAmyZNLWcbnAp8hrUUQsFfMaey',	3,	'charles.rubio@lycee-guychauvet.fr');

DROP TABLE IF EXISTS "roles";
CREATE TABLE "public"."roles" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "lib" character varying(255) NOT NULL,
    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "roles" ("id", "lib") VALUES
(1,	'EntraÎneur'),
(2,	'Utilisateur'),
(3,	'Administrateur');

DROP TABLE IF EXISTS "session";
CREATE TABLE "public"."session" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nb_place" integer NOT NULL,
    "heure_deb" time without time zone NOT NULL,
    "heure_fin" time without time zone NOT NULL,
    "date_deb" date NOT NULL,
    "date_fin" date NOT NULL,
    "activite_id" integer,
    "entraineur_id" integer,
    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "idx_d044d5d49b0f88b1" ON "public"."session" USING btree ("activite_id");

CREATE INDEX "idx_d044d5d4f8478a1" ON "public"."session" USING btree ("entraineur_id");


DROP TABLE IF EXISTS "type";
CREATE TABLE "public"."type" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "lib" character varying(255) NOT NULL,
    CONSTRAINT "type_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "type" ("id", "lib") VALUES
(1,	'Equipe'),
(2,	'Raquette'),
(3,	'Combat');

ALTER TABLE ONLY "public"."activite" ADD CONSTRAINT "fk_b8755515c54c8c93" FOREIGN KEY (type_id) REFERENCES type(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."inscrire" ADD CONSTRAINT "fk_84ca37a8613fecdf" FOREIGN KEY (session_id) REFERENCES session(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."inscrire" ADD CONSTRAINT "fk_84ca37a86a99f74a" FOREIGN KEY (membre_id) REFERENCES membre(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."membre" ADD CONSTRAINT "fk_f6b4fb29d60322ac" FOREIGN KEY (role_id) REFERENCES roles(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."session" ADD CONSTRAINT "fk_d044d5d49b0f88b1" FOREIGN KEY (activite_id) REFERENCES activite(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."session" ADD CONSTRAINT "fk_d044d5d4f8478a1" FOREIGN KEY (entraineur_id) REFERENCES membre(id) NOT DEFERRABLE;

-- 2026-01-22 11:31:10.006474+01